name: Translations

on:
  push:
    branches: [ main ]
    paths:
      - 'rare/languages/placeholder.ts'
  workflow_dispatch:

jobs:

  appimage:
    runs-on: ubuntu-20.04
    env:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: install Deps
        run: |
          sudo apt update
          sudo apt install python3 python3-pip python3-setuptools
          pip install transifex-client

      - name: push file
        run: tx push -s
